apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: tst-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCvmR0XhwNKhyKY5mYnnftvVpugWxaqm+WyyrsVYZxcz297vQ46Isgct5ZU5lz8C46KAzeXPfFBeSNOIYb2j82pM1juso3uYBLUr74u/ZsrAGtUcSZ4ct74MIilMAd30TILJ43WqHDT9DVj6N7FrKm+gVmSHpFNqqrBqUeEA7crMJuS0GiS/foMNa/qo4u6gJkGpvROtm/dPrqYCN6PMojfLYRURr/pQXDK9k+oXfXPWvj3qmiSenA0Pf4TyrofxTKd3Kaw0iMoCZvAaiFoaxqLC3uPngYu/MKrPiWWreONqZHGG0N9j7fFK6YjzD1c+AYQ5eY9x1th7VSJ774bhazOg8LLD8yfksp6S5dVvuajUENkg5oZDLxJT0x/BGM7ZYHDkAD5v0La1+CIyY86JoxcVbyd/sXuR/5vFoAiA5D4e7h7RZzZ/RvnRmCMWBdBSX3eE2sG1st+oVSARlz/Y6f0qgMDk8bkjaIf2SX0GLPBKWuHKGEw2La5880+9x/0W8RMlKRxcs+bi8cxO6KEdqf/cQ2yD0bPJzeFoKVjQK0J+VokYc1zk9XaJNHqCdGh2NxzObATl2Bvm4ZK94PlOTdZLMpiEz7fJGGYUIJXwUkxWVaUjnfeH7+7sGKhnLSJRsMM7jM07jYLhJ3OCVRJAreWkc3fTLccaJlm+sOaFOU7YEgRdgpnJdfHjCMdoUA6FdQ5IZJFrVMKCopxmrfx9vIkpa/hgMkKlKQJOUlrTcERLNmrshQcNhmcPp8WwET3yxn23aMW819sRvlYRnStxHGpQ9ka6MdRGiQVWg8fb8fjMq435H5C497M9nAQ4QpoECpfUAFxc45o/uLmewCkp+R57JjMErd8Qr1alpM0hA3FI1rz2BXvaoq2xeVoFGqXhnvgBTOBAcC6w1wYCyPeWp+59FpSGti9ls8GAxJNeB70
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: tst-cicd
    type: kubernetes.io/dockerconfigjson
status: {}
