apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-bose-dev-fruit-app
  namespace: bose-cicd
spec:
  encryptedData:
    webhook-secret-key: AgAF9mgBVZkg95piDd8F9fbrrUluwKmPltvLhYhkL43wqRzL8i7Xi29+2OkpHQhSpb8xxzmZk1q82qbGIZvdkVLr3CCQW9Z/jkidpoS1ga02cEglKIatAXOQXQW6w++BwlasTTmudGpDHgN6K1+15GDDTAiHnylAK6B9yiWCqKhm+v0CCJveToMfgwix+I7yYG27VbjBSEQMl+6EZCygNByrX8GTu3yMW+kyoNogVutRdroyygwQ/iOm3upJ54d2l21y62eIpblcArHMTFJ7P7+2P1UDC7sCRxuayIH2a52EIUhFlCJ8ycUTNhuYm/hdXXl1rSUZ8KJMsY5kzeDcuzrLL+f6Scg9/AiCT/18TcziMaQc4/J/uhisF2j4H8x+3RSC2EADfxngevAs6CrL0Hi78Yt0ESAccJmSemRJGtLQbskxkKuYgs8cv3p9MPuSoltkLis/5NBRADNM6KV06qR977xNBic/DEW1U7HQAYe3OOLJb/XIR7qJ4utz/S31iZAhcc06U0gebca5657P7KRpdd3Vzic4Qsqk/Wmb4Ru42me7IaF3Zsf6drMY/CpwmKKfqCRKPDyYVznh4IxjvSa/D/8GmKxgAQwECml72kz8uj/GnV1P+85u4i+wYGWuMWr4gIVTenhHJ2LP9s1aHdZ8sikk5YowINhs5Yv/etyeMrrxsyUMNLH5k0/S8cz/VGT3C7jELIWMeB6QG8xc43S6Ya+X/A==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-bose-dev-fruit-app
      namespace: bose-cicd
    type: Opaque
status: {}
