apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-bose-dev-inventory
  namespace: bose-cicd
spec:
  encryptedData:
    webhook-secret-key: AgCv7xZlzYyYsTEpYuD9KfxTUxfsHvD2/LJpEwp7dY/aL83dCQPtA17fWH32TrGcXF9xz/GgvGLoCm13AbljzkUqLH2X5vGU8d0AA8eS6L3sZQziFQfArINBJ/n3eH7aDzSEHL3oqaaUtQSBvLLduLvfQRXrahvIDfB/CLe+7f3hMoWWMod68c0KpA4DsdkPRrIis/iEMe9AlKj+PC6h1z1Cx0raDWbFzv0TiWXsWfj3BB7qDh5RaQ0P9WrfZtJu7R7TbDyqyHvqCumHD0wghrMhXNzBE65130vLsgjKQBGHsvHSbE55XyA6s+C7tLMaeR6tDwXYyRGCaNaJ3yIxJkbv9B2N8cuUvvt+EBy87NVhzCsiyqiXfSwy/yvW8UdzYMYH1nirvn2wavum76xRnBgJ3NwUwxtnqEiueuzkKuu4De+2wCdypG7n/DqdBQGVxK6mAdQ7Iph0BT9ySBYffvWVjtw28H5IHqazOu/NoDcYodSHtmj5PZpITH3YDVzKqE2yT762DesrRkTHHHFAZoLbHBrkibwtuKEr+E/nE+yWr1pXi7Kb5Lf9/mJN/Iqri+LtIVoh7P8VLfNmMcCmM1NaAWPJyCMx4WrWmJjCZm0UsiTXBD0LtPQr6ehYbkdmoYqjaYCixHAZ0CPEtSXiKwCMxbWLtU0lF2H30cEJMkYMN7uZnpN7XVAdwlFoiD02K4xPoEScnaRn3Qp83+XAHfGwkiaz2Q==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-bose-dev-inventory
      namespace: bose-cicd
    type: Opaque
status: {}
