apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: ford-cicd
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: github-pr-binding
    interceptors:
    - cel:
        filter: (header.match('X-GitHub-Event', 'pull_request') && body.action ==
          'opened' || body.action == 'synchronize') && body.pull_request.head.repo.full_name
          == 'sbose78/gitops'
    - github:
        secretRef:
          namespace: ford-cicd
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
    name: ci-dryrun-from-pr
    template:
      name: ci-dryrun-from-pr-template
  - bindings:
    - name: github-push-binding
    interceptors:
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'sbose78/gitops') && body.ref.startsWith('refs/heads/master')
    - github:
        secretRef:
          namespace: ford-cicd
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
    name: cd-deploy-from-push
    template:
      name: cd-deploy-from-push-template
  - bindings:
    - name: ford-dev-fruit-app-binding
    - name: github-pr-binding
    interceptors:
    - cel:
        filter: (header.match('X-GitHub-Event', 'pull_request') && body.action ==
          'opened' || body.action == 'synchronize') && body.pull_request.head.repo.full_name
          == 'sbose78/fruit-app'
    - github:
        secretRef:
          namespace: ford-cicd
          secretKey: webhook-secret-key
          secretName: webhook-secret-ford-dev-fruit-app
    name: app-ci-build-from-pr-fruit-app
    template:
      name: app-ci-template
status:
  configuration:
    generatedName: ""
