apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: ford-dev-app-fruit-app
  namespace: argocd
spec:
  destination:
    namespace: ford-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/ford-dev/apps/app-fruit-app/base
    repoURL: https://github.com/sbose78/gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
