apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: taxi
  namespace: tst-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: taxi
      app.kubernetes.io/part-of: app-taxi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: taxi
        app.kubernetes.io/part-of: app-taxi
    spec:
      containers:
      - image: quay.io/shbose/fruit-app:v0.0.1
        imagePullPolicy: Always
        name: taxi
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
